user1 = User.create(firstname: "Dayne", lastname: "Dewar", age: 25, bio: "Fun dude with a cool tude", location: "Brooklyn, NY", rating: 10)

sport1 = Sport.create(name: "Volleyball", equipment: "volleyball", rules: "Each team consist of 6 players and 6 substitutes. Players can be substituted at any time but if they are to return can only be swapped for the player that replaced them. Each team can hit the ball up to three times before the ball must be returned. The defensive team can then try and block or return the ball again hitting it a maximum of three times. Games are played up to 25 points and must be won by 2 clear points. Violations will be called for the following: 1. Stepping over the base line when serving the ball. 2. Ball hits the net and fails to get over the net (If the ball hits the net and still goes over the net then this is perfectly legal). 3. Players are not allowed to carry, palm or run with the ball. 4. Players must not touch the net with any part of the body. If the net is said to have hit them rather than vice-versa, then this is ok. 5. The ball cannot travel under the net. 6. Players cannot reach over the net and hit the ball.", image: "https://3er1viui9wo30pkxh1v2nh4w-wpengine.netdna-ssl.com/wp-content/uploads/prod/sites/93/2018/05/FIVB-vball-960x640.png", user_id: 1)
sport2 = Sport.create(name: "Basketball", equipment: "basketball", rules: "Each team can have a maximum of 5 players on the court at any one time. Substitutions can be made as many times as they wish within the game. The ball can only be moved by either dribbling (bouncing the ball) or passing the ball. Once a player puts two hands on the ball (not including catching the ball) they cannot then dribble or move with the ball and the ball must be passed or shot. After the ball goes into a team’s half and they win possession back the ball must then make it back over the half way line within 10 seconds. If the ball fails to do so then a foul will be called and the ball will be turned over. Each team has 24 seconds to at least shot at the basket. A shot constitutes either going in the basket or hitting the rim of the basket. If after the shot is taken and the ball fails to go in the basket then the shot clock is restarted for another 24 seconds. The team trying to score a basket is called the offence whilst the team trying to prevent them from scoring is called the defence. The defence must do all they can to stop the offence from scoring by either blocking a shot or preventing a shot from being fired. After each successful basket the ball is then turned over to the opposition.", image: "https://eyofbaku2019.com/images/sport%20pages/basketball.jpg", user_id: 1)
sport3 = Sport.create(name: "Football", equipment: "football", rules: "Games last for four 15 minute quarters. A 2 minute break between the 1st & 2nd and 3rd & 4th quarters is had along with a 15 minute rest between 2nd and 3rd quarters (half time). Each team has 4 downs to gain 10 or more yards. They can either throw or run the ball to make the yards. As soon as the team gains the required yards then the downs reset and the yardage resets. Failure to make the yardage after 4 downs will result in a turnover. There are hundreds of different plays that players can run on any down. Plays are made up by the teams and often have players running all over the place (routes) in what is essentially organised chaos. The head coach or quarter back calls the on field plays for the attacking team whilst the defensive captain calls the plays for the defensive team. At the start of every game is the coin toss to decide which team receives the ball first and which side of the pitch they want to start from. The game begins with a kick-off where one team punts the ball down field for the other team to then run back with the ball as far as possible. On fourth down the offence has the option to either try to make up the yards they are short or to kick the ball. If they decide to kick they have two options; to punt or to try for a field goal. Depending on their position on the pitch will usually dictate their paly. Anything within 40 yards or so of the opposition’s goal posts will result in a field goal attempt. Further back will likely mean they take the punt option.", image: "https://sports.nbcsports.com/wp-content/uploads/sites/11/2020/08/GettyImages-1188526707.jpg", user_id: 1)
sport4 = Sport.create(name: "Soccer", equipment: "soccer ball", rules: "A match consists of two 45 minutes halves with a 15 minute rest period in between. Each team can have a minimum off 11 players (including 1 goalkeeper who is the only player allowed to handle the ball within the 18 yard box) and a minimum of 7 players are needed to constitute a match. The field must be made of either artificial or natural grass. The size of pitches is allowed to vary but must be within 100-130 yards long and 50-100 yards wide. The pitch must also be marked with a rectangular shape around the outside showing out of bounds, two six yard boxes, two 18 yard boxes and a centre circle. A spot for a penalty placed 12 yards out of both goals and centre circle must also be visible. The ball must have a circumference of 58-61cm and be of a circular shape. Each team can name up to 7 substitute players. Substitutions can be made at any time of the match with each team being able to make a maximum of 3 substitutions per side. In the event of all three substitutes being made and a player having to leave the field for injury the team will be forced to play without a replacement for that player. Each game must include one referee and two assistant referee’s (linesmen). It’s the job of the referee to act as time keeper and make any decisions which may need to be made such as fouls, free kicks, throw ins, penalties and added on time at the end of each half. The referee may consult the assistant referees at any time in the match regarding a decision. It’s the assistant referee’s job to spot offside’s in the match (see below), throw ins for either team and also assist the referee in all decision making processes where appropriate. If the game needs to head to extra time as a result of both teams being level in a match then 30 minutes will be added in the form of two 15 minute halves after the allotted 90 minutes. If teams are still level after extra time then a penalty shootout must take place. The whole ball must cross the goal line for it to constitute as a goal. For fouls committed a player could receive either a yellow or red card depending on the severity of the foul; this comes down to the referee’s discretion. The yellow is a warning and a red card is a dismissal of that player. Two yellow cards will equal one red. Once a player is sent off then they cannot be replaced. If a ball goes out of play off an opponent in either of the side lines then it is given as a throw in. If it goes out of play off an attacking player on the base line then it is a goal kick. If it comes off a defending player it is a corner kick.", image: "https://bcrams.com/images/2018/10/1/Soccer_picture.jpg", user_id: 1)

event1 = Event.create(location: "Domino Park", equipment: true, sport_id: 1)
event2 = Event.create(location: "Central Park", equipment: true, sport_id: 4)
event3 = Event.create(location: "Pier 6", equipment: false, sport_id: 3)

user_event1 = UserEvent.create(user_id: 1, event_id: 1)
user_event2 = UserEvent.create(user_id: 1, event_id: 2)
user_event3 = UserEvent.create(user_id: 1, event_id: 3)

puts '🔥🔥🔥🔥🔥'